
num_objs: 10
batch_size: 10
pack_type: "random"
object:
  ID : 23
  bop_dataset_path : "/home/mujin/sandbox/mujin/repos/datasets/bop"
  bop_dataset_name: "hope"
  mm2m : true
scene:
  _target_: scene.Scene
  cfg:
    simulation:
      min_sim_time: 3
      max_sim_time: 5
      check_object_interval: 1
      substeps_per_frame: 20
      solver_iters: 25
    camera:
      location: [0, 0, 1]
      intrinsics:
        fx : 2765.610107421875
        fy : 2765.087158203125
        cx : 964.0423768127082
        cy : 583.8270604909656
      image_size:
        w : 1920
        h : 1080
    floor:
      extents: [5, 5, 5]
      location: [0, 0, -5]
    light:
      energy : 200
      color: [0.5, 0.5, 0.5]
      location: [0, 0, 1.02]
    light_plane:
      emission_strength : 5.36
      emission_color: [0.5, 0.5, 0.5, 1.0]
      extents: [2, 2, 1]
      location: [0, 0, 1.5]
    container:
      model_file : "/home/mujin/tmp/container.ply"
      extents: [0.4, 0.2, 0.2]
      thickness: 0.02
      texture_dir : "/home/mujin/sandbox/mujin/repos/BlenderProc/resources/cctextures/Plastic008/"
dataset:
  output_dir : "/home/mujin/sandbox/mujin/repos/datasets/bop/ucn_2"
  name : "hope"
  rgb_img_format : "PNG"
  ignore_dist_thres: 10
