defaults:
  - object: raisins
  - scene: base

num_objs: 10
batch_size: 10
pack_type: "random"
dataset:
  output_dir : "/home/mujin/sandbox/mujin/repos/datasets/bop/ucn"
  name : "hope"
  rgb_img_format : "PNG"
  ignore_dist_thres: 10
  num_scenes: 10
  num_poses_per_scene: 1
