defaults:
  - _self_
  - object: raisins
  - scene: base

num_objs: 10
batch_size: 10
pack_type: "random"
dataset:
  output_dir : "/home/kln/sandbox/cmu/repos/capstone/datasets/bop/ucn_test"
  name : "hope"
  rgb_img_format : "PNG"
  ignore_dist_thres: 10
  num_scenes: 10
  num_poses_per_scene: 1
